#.yarnrc.yml is internal setting installed automatically

# If you want to use previous way managing package.
# Enable below option
# nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs
