openapi: 3.0.3
info:
  title: Fastify-Typescript-Project
  description: This is for testing fastify with typescript
  version: 1.0.0
components:
  schemas:
    def-0:
      type: object
      properties:
        id:
          type: number
          format: int64
          minimum: 1
        name:
          type: string
        email:
          type: string
          format: email
        registerDate:
          type: string
          format: date-time
      title: user
    def-1:
      type: object
      properties:
        name:
          type: string
        publishDate:
          type: string
          format: date-time
        author:
          type: string
      title: book
paths:
  /users:
    get:
      tags:
        - users
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      format: int64
                      minimum: 1
                    name:
                      type: string
                    email:
                      type: string
                      format: email
                    registerDate:
                      type: string
                      format: date-time
        '404':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
                  statusCode:
                    type: number
  /users/{userId}:
    get:
      tags:
        - users
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    format: int64
                    minimum: 1
                  name:
                    type: string
                  email:
                    type: string
                    format: email
                  registerDate:
                    type: string
                    format: date-time
        '403':
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
                  statusCode:
                    type: number
  /books:
    get:
      tags:
        - books
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    publishDate:
                      type: string
                      format: date-time
                    author:
                      type: string
  /books/{bookName}:
    get:
      tags:
        - books
      parameters:
        - in: path
          name: bookName
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  publishDate:
                    type: string
                    format: date-time
                  author:
                    type: string
servers:
  - url: http://localhost
tags:
  - name: books
    description: Books operations
  - name: users
    description: Users operations
